name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'new-release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest draft release
        id: get-latest-draft
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const draftRelease = releases.find(release => release.draft === true);
            if (draftRelease) {
              return draftRelease.id;
            }
            return '';
          result-encoding: string

      - name: Publish draft release
        if: steps.get-latest-draft.outputs.result != ''
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.get-latest-draft.outputs.result }},
              draft: false
            });
