name: Update Package Version

on:
  workflow_run:
    workflows: ["Release Drafter"]
    types:
      - completed

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Get draft release version
        id: get-version
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const draftRelease = releases.find(release => release.draft === true);
            if (!draftRelease) {
              throw new Error('No draft release found');
            }

            const version = draftRelease.tag_name.replace(/^v/, '');
            console.log(`Draft release version: ${version}`);
            return version;

      - name: Update package.json version
        run: |
          VERSION="${{ steps.get-version.outputs.result }}"
          npm version $VERSION --no-git-tag-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update package.json version to ${{ steps.get-version.outputs.result }}"
          title: "chore: update package.json version to ${{ steps.get-version.outputs.result }}"
          body: |
            Update package.json version to match the latest draft release version.
            This PR was automatically created by GitHub Actions.
          branch: "new-release"
          base: "main"
          delete-branch: true
